apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
      - name: dbinit
        image: lbogdan/movies-api:v6
        args: ["db-init"]
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: movies-secret
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: movies-secret
                key: DATABASE_PASSWORD
        # envFrom:
        # - secretRef:
        #   name: movies-secret
        volumeMounts:
        - name: config-volume
          mountPath: /app/config

      restartPolicy: OnFailure
      volumes:
      - name: config-volume
        configMap:
          name: config-json
  backoffLimit: 10
